#!/usr/bin/env bash

# Provoke empty responses from oscars-01.vgt.vito.be; run on an epod for great justice.

set -eo pipefail

function send_mail() {
  local subject=$1
  local body=$2

  echo "$body" | mailx -v -s "$0: $subject" -S smtp=smtp://zimbra.vgt.vito.be jan.van.den.bosch@devoteam.com
}

function do_request() {
  local client_id=$1
  local output_file=products.json

  # curl --fail --output "${output_file}" "http://oscars-01.vgt.vito.be:8080/products?collection=urn:eop:VITO:TERRASCOPE_S2_FAPAR_V2&start=2017-08-04T00:00:00&end=2017-12-29T23:59:59&bbox=5.07036,51.207300000000004,5.0903599999999996,51.2273&clientId=${client_id}"
  wget -qO- --output-document "${output_file}" --content-on-error "http://oscars-01.vgt.vito.be:8080/products?collection=urn:eop:VITO:TERRASCOPE_S2_FAPAR_V2&start=2017-08-04T00:00:00&end=2017-12-29T23:59:59&bbox=5.07036,51.207300000000004,5.0903599999999996,51.2273&clientId=${client_id}"

  #if jq -c "." "${output_file}" > /dev/null; then
  json_type=$(jq -r 'type' "${output_file}" | sed -e 's/^\s*//' | sed -e 's/\s*$//')

  if [ "$json_type" = "object" ]; then
    rm "${output_file}"
  else
    send_mail "parsing response failed" "$(cat ${output_file})"
    exit 1
  fi
}

while true; do
  client_id=$(uuidgen)
  echo "$client_id"
  do_request "$client_id"
  sleep 5
done

